name: Backend Tests and Docker Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Spotify-Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install


      - name: Log in to Docker Hub
        if: success() && github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        if: success() && github.ref == 'refs/heads/main'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spotify-backend:latest .

      - name: Push Docker image
        if: success() && github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spotify-backend:latest
